### ISSUE TITLE
where to get the file 'unix_sock.data'?

### ISSUE THREAD

**Issue by heshule** [feiin/node-xdag#1]
where to get the file 'unix_sock.data'? 

i`d like to test a dapp function, but cant find out the file unix_sock.data.

**Comment by yangyin5127** [comment]
in the xdag directory  ,`unix_sock.dat`
@heshule

**Comment by ncgege** [comment]
thank your for your hard work. It's very usefull.
do you in the xdag dev team?
can you message me ,when you are convenient.
My QQ is 8160903,thanks.
